### PR TITLE
Add reset-flow button (fixes openspending/openspending#867), use correct name for resources (fixes openspending/openspending#863)

### PR DESCRIPTION
**Pull request by akariv**

### CODE REVIEW

**Comment by akariv** [comment]
Fixes: openspending/openspending#863
Fixes: openspending/openspending#867

**Comment by pwalsh** [comment]
@akariv tests fail?

**Comment by akariv** [comment]
There's a flaky test there I think. I'll try to see if I can fix it.

**Comment by akariv** [comment]
@pwalsh plz take a look

**Comment by pwalsh** [comment]
@akariv ok go for it.

**Pull request merged**
